Issue 3 union support
coldbox-modules/qb pull request #50
Opened 2018-08-15 21:06 UTC by dswitzer

Fixes issue #3 by adding support for UNION and UNION ALL. You can either feed in another QB to the union() and unionAll() methods or use a closure to define the query.

2018-08-16 02:44 UTC, elpete requested changes

2018-08-16 02:44 UTC, elpete commented on models/Grammars/BaseGrammar.cfc
> +            if( arguments.union.query.getOrders().len() ){
Let's do this check first so we don't waste time converting the SQL if there are order bys.

2018-08-16 02:44 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +    * @all Determines if UNION statement should be a "UNION ALL".  Passing this as an argument is discouraged.  Use the dedicated `unionAll` where possible.
I like the note about this argument being discouraged in favor of `unionAll` 👍

2018-08-16 02:47 UTC, elpete commented
Also, can you please add this to the docs: https://github.com/ortus-docs/qb-docs

2018-08-16 17:10 UTC, dswitzer commented on models/Grammars/BaseGrammar.cfc
> +            if( arguments.union.query.getOrders().len() ){
I've made the change.

2018-08-16 19:13 UTC, dswitzer commented
Shouldn't we wait to document the changes once the code is merged?

2018-08-16 21:43 UTC, elpete commented
I’ll merge both when they exist.

2018-08-17 13:25 UTC, dswitzer commented
I've put up a pull request for the UNION docs:

https://github.com/ortus-docs/qb-docs/pull/13

2018-08-17 18:13 UTC, elpete approved these changes

2018-08-17 18:13 UTC, merged