Qb 12 unicode text functions
coldbox-modules/qb pull request #57
Opened 2018-09-07 22:46 UTC by MordantWastrel

This isn't ready for prime time yet but I think it's pretty close, depending on some assumptions I made about how and when unicodeString should be employed. 

It's failing two postgres tests related to ALTER TABLE where it relies on the getType() and the approach I took for this is inconsistent with the assumption that getType() will always return a valid data type for your grammar – or else there's an easy way to make UNICODETEXT just TEXT for that grammar that I missed. I didn't see right away where to override the type set in the blueprint for cases where a grammar doesn't actually have a datatype and you need it to behave like a different one.

2018-09-10 20:14 UTC, elpete requested changes
Looks good.  I added a few comments that I'd like to resolve before merging.  Thanks!

2018-09-10 20:14 UTC, elpete commented on tests/specs/Schema/PostgresSchemaBuilderSpec.cfc
> +        return longText();
I would prefer, in the tests, to return the expected value in each function, even if it is duplicated.  I think that makes it 1) more clear what the test is expecting and 2) easier to change in the future if the two diverge.  Can you please update all of these locations in the tests?

2018-09-10 20:14 UTC, elpete commented on tests/resources/AbstractSchemaBuilderSpec.cfc
> -                        table.string( "username" );
Can you walk me through why we changed all these from `string` to `unicodeString`?  I don't think it was necessary.  It also seems to have inadvertently removed any test referencing `table.string` and so the removal of `typeString` from the MSSQL Grammar was not caught.

2018-09-10 20:14 UTC, elpete commented on models/Grammars/MSSQLGrammar.cfc
> -    function typeString( column ) {
Why was `typeString` removed here?  I'm pretty sure this breaks existing functionality.

(It looks like `table.string` was changed to `table.unicodeString` in all the tests which is why this wasn't caught by the tests.)

2018-09-10 20:14 UTC, elpete commented on models/Grammars/PostgresGrammar.cfc
> +            generateType( commandParameters.to, blueprint ) & ",",
This was the fix for the wrong type for modify column statements.

2018-09-10 20:20 UTC, DiscountDarcy commented on tests/resources/AbstractSchemaBuilderSpec.cfc
> -                        table.string( "username" );
I used unicode for fields that I considered would be candidates to be unicode in practice -- names (definitely) and usernames (maybe?). But it makes no difference to me.

2018-09-10 20:20 UTC, DiscountDarcy commented on models/Grammars/MSSQLGrammar.cfc
> -    function typeString( column ) {
I removed it because the definitions on BaseGrammar are (as of this PR) now correct for MSSQL such that no child definition should be necessary. But I don't have it in front of me ATM so if I'm mistaken I'm happy to put it back.

2018-09-10 20:27 UTC, elpete commented on models/Grammars/MSSQLGrammar.cfc
> -    function typeString( column ) {
Ahhh....I see now.  It's using the parent class.  Sorry.  False alarm.

2018-09-10 20:27 UTC, elpete commented on tests/resources/AbstractSchemaBuilderSpec.cfc
> -                        table.string( "username" );
Hmmm...I suppose this makes sense.  Thanks for explaining.

2018-09-10 22:54 UTC, MordantWastrel commented on tests/specs/Schema/PostgresSchemaBuilderSpec.cfc
> +        return longText();
It wasn't that they were duplicated, but that (as far as I know) Postgres doesn't have any concept of a separate datatype for this. It's sort of the test spec's way of expressing that the unicodeLongtext for Postgres should be the longText test. While they could diverge, that seems unlikely.

Having said that, I have no problem changing this; and I'm not sure I was consistent across all grammars with this behavior either.

2018-09-11 00:24 UTC, elpete commented on tests/specs/Schema/PostgresSchemaBuilderSpec.cfc
> +        return longText();
That’s an interesting and valid perspective. Let’s leave it for now to signal that the implementations should be identical. Thanks.

2018-09-11 00:29 UTC, merged

2018-09-11 00:30 UTC, elpete commented
Last step @MordantWastrel is to document this over on ortus-docs/qb-docs.

2018-09-11 01:17 UTC, MordantWastrel commented
I'll add something about unicodeString tomorrow.

2018-09-11 16:10 UTC, MordantWastrel commented
https://github.com/ortus-docs/qb-docs/pull/20