preventDuplicateJoins and tests
coldbox-modules/qb pull request #82
Opened 2020-02-13 15:26 UTC by MordantWastrel

https://ortussolutions.atlassian.net/browse/QB-43

2020-03-05 22:23 UTC, elpete requested changes
A few minor changes (and rebasing off of master).  I would do the minor changes myself, but GitHub isn't allowing me.

Lastly, when all the changes are done, will you please run `box run-script format` on the repo, commit, then push that up.  The formatting linting isn't failing until I use CommandBox 5 in Travis.

2020-03-05 22:23 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +            if ( local.hasThisJoin ) {
Can we lose the `local`?

2020-03-05 22:23 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +                if ( local.hasThisJoin ) {
Can we lose the `local`?

2020-03-05 22:23 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +            this.getMementOForComparison(),
Lowercase `O` on memento?

2020-03-05 22:23 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +            else if ( variables.unions.some( function( u, index ) {
Instead of nesting the `.some` call in an `else if` block, can we pull this out and use a plain ole `if` after doing the `.some`?  It would help me read it better.

2020-03-05 22:23 UTC, elpete commented on models/Query/QueryBuilder.cfc
> +                local.memento[ "from" ] = ( isSimpleValue( getFrom() ) ? getFrom() : getFrom().getSQL() );
Not sure if you have a test for this, but I believe it is `toSQL` not `getSQL`.

2020-03-05 22:23 UTC, elpete commented on tests/specs/Query/Abstract/JoinClauseSpec.cfc
> +                        structDelete( variables, "join2" );
Perhaps you mean `joinOther` here?

2020-03-06 03:28 UTC, MordantWastrel commented
Closed in favor of a PR rebased onto master with requested changes.

2020-03-06 03:28 UTC, closed without merging